import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Header } from '@/components/Layout/Header';
import './globals.css';
import { getCartItemsDb } from '@/utils/getCartItemsDb';
import { cookies } from 'next/headers';
import { getTotalItemQuantity } from '@/utils/getTotalItemQuantity';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const cookieStore = cookies();

    const items = await getCartItemsDb(cookieStore);
    const count = getTotalItemQuantity(items);

    return (
        <html lang='en'>
            <head>
                <meta charSet='utf-8' />
                <link
                    rel='icon'
                    type='image/svg+xml'
                    href='/favicon.svg'
                />
                <meta
                    name='viewport'
                    content='width=device-width'
                />
                <title>Mcpickle Next fruit</title>
            </head>
            <body className={inter.className}>
                <Header count={count} />
                <div className='bg-gray-50 p-8'>{children}</div>
            </body>
        </html>
    );
}
